# 결론: 편리할 것은 편리하게, 불편할 것은 불편하게

인간은 자기 중심적이기 때문에 누구나 자신이 하는 일은 고평가하고 남이 하는 일은 저평가한다. 훌륭한 사람은 남을 낫보다 낫게 여기겠지만 우리 대부분은 나 자신을 다른 사람보다 낫게 여긴다. 한국 사회는 전통적으로 책상에 앉아서 문서로 판단을 하는 사람들이 사회의 주류를 이루는 관료 사회다. 그러다 보니 실제로 무엇을 하는 사람보다, 남에게 그 일을 시키는 사람들이 대우를 받는다. 직접 자기 손으로 무언가를 만드는 일의 가치를 낮게 평가한다. 미국에서는 의사, 변호사 못지 않게, 어쩌면 더 사회적으로 존경받고, 경제적으로 보상받는 전문가 집단이 엔지니어다. 엔지니어는 학계, 기업, 정부 등 어느 분야에든 진출할 수 있고, 본인이 기술이 있으니 원하면 창업도 쉽게 할 수 있다. 그리고 그렇게 해서 성공한 사례가 무수히 많다. 단적으로 미국 경제의 혁신을 견인하는 캘리포니아의 역사가 이러한 기술 발전의 역사다. 캘리포니아라는 주의 탄생 자체가 골드 러쉬로 탄생했다. 캘리포니아 주가 황금의 주(The Golden State)라고 불리는 이유는 19세기말 그곳에서 금광이 발견했기 때문이다. 황금을 찾아 미국 전역에서, 전세계에서 광부들이 몰려들었고, 당대의 첨단 산업인 광업을 꽃피웠다. 중국에서 미국으로 이민이 시작된 것도 이 시기고, 이때 미국에서 최초로 샌프란시스코에 차이나 타운이 만들어졌다. 필자가 졸업한 UC 버클리가 이렇게 몰려든 주의 젊은 인구들을 교육 시키고자 만들어진 캘리포니아 대학의 첫 번째 캠퍼스다. 지금은 실리콘밸리에서 혁신의 미래를 꿈꾸고자 전세계의 젊은이들, 특별히 엔지니어들이 몰려든다. 워낙 인도, 중국에서 몰려온 엔지니어들이 많다 보니 실리콘밸리가 있는 사우스베이(샌프란시스코의 남쪽)는 인구 구성을 볼 때 백인보다 아시안이 더 많다. 서울에서는 카페에 가서 커피를 마시고 있으면 취업을 위해 시험 공부를 하는 한국인 젊은이들을 흔하게 보는데, 샌프란시스코 베이 에어리아(샌프란시스코 항만 인근 지역)에서는 코딩을 하거나 창업을 이야기하는 다양한 인종과 국적의 젊은이들을 흔하게 본다.

공공 부문에 데이터 사이언스가 도입이 되려면 기술이 중시가 되어야 한다. 이제 고인이 된 애플의 창업자 스티브 잡스가 IT의 미래는 기술과 학문간 경계를 넘나드는 광범위한 교양(liberal arts)에 있다 했다. 한국에서는 인문학이라 번역하는 리버럴 아츠는 사실 문사철에 한정되지 않는다. 미적분학도 인류의 가장 우수한 지적 발견 중 하나로, 당연히 교양의 일부다. 상식의 확대를 위해 플라톤의 국가론을 읽고 마키아벨리의 군주론을 읽어야 한다면, 같은 맥락에서 미적분학을 배워야 하고 통계학을 배워야 한다. (요즘은 경제학, 정치학, 심리학, 사회학 등 각종 분야의 사회과학도들도 데이터를 가지고 연구를 하는 사람들이면 정량적 방법론이란 이름 하에 이런 것들을 다 배운다.) 그러나 교양이 방향을 잡아줄 수는 있으나, 그것으로는 충분하지 않는다. 데이터 사이언스나 인공 지능 같은 것들도 개념적인 부분을 책이나, 강연으로 배울 수는 있다. 책과 강연을 통해 배우는 것은 중요하다. 직접 경험을 통해 배울 수 있는 지식의 폭은 한계가 있기 때문이다. 그러나 이런 학습법에 한계도 분명히 있다. 책과 강연은 개념적인 내용을 이해시키는 데 초점을 두기 때문에 가장 쉽고 깔끔한 예를 사용한다. 그러나 현실에서 데이터를 다루면 그 데이터들은 책에서는 구경도 못해본 지저분한 데이터가 대부분이다. 결과도 해석이 분명하게 나오지 않는 경우가 많다. 데이터를 실제 다뤄보지 않으면, 모형을 실제 만들어 보고, 적용해 보고, 해석해 보지 않으면 이렇게 실전에서 알게 되는 온갖 애로사항에 무지하다.

그러나 기술적 지식은 문제 해결을 위한 한 변수일 뿐이다. 기술을 면밀히 안다고 해도 그것을 어떻게 적용할 줄 안다고 해도, 언제, 어디에, 무엇을, 왜 적용할지 모르면 기술의 응용이 불가능하다. 그래서 다른 큰 변수는 문맥적 지식이다. 그 치열하다는 요식업에서 살아남기 위해서는 어떻게 해야 할까. 맛있는 음식을 만드는 것은 필요조건이다. 그러나 그것만으로는 부족하다. 소비자를 알아야 한다. 자신이 만드는 음식을 먹을 사람이 누구이며, 그 사람이 어떤 음식을, 왜 좋아하는지, 언제, 어디에서 먹는 것을 선호하는지를 알아야 한다. 재정, 인사, 운영에 대해서 알아야 한다. 그렇게 음식을 만드려면 얼마나 비용이 들고, 그 비용을 감당하기 위해서는 어떻게 음식을 준비해야 하고, 어떻게 팀을 꾸려야 하는 지를 알아야 한다. 나아가, 상황이 다양하고, 그 다양한 상황이 빠르게 편하니, 그에 맞춰 신속하고 유연하게 전략을 바꿔나갈 줄 알아야 한다. 조직에 따라서 데이터의 성숙도가 다르다. 아직 인프라도 구축되지 않은 조직은 일단 데이터 인프라부터 만들어야 한다. 데이터가 어디서 들어와서 어디로 나가는 지를 파악하고, 그 과정(data pipeline)을 효율적으로 자동화한다. 이런 조직에서는 조직 구성원의 데이터 이해 능력이 부족할 가능성이 크니 그에 대한 조직 내의 데이터 해석 능력 제고를 위한 교육도 필요하다. 이런 기초가 갖춰진 다음에야 보다 고도화된 데이터 전략을 구상해볼 수 있다.

나아가, 문제 정의 자체가 문제다. 여기서도 문맥적 지식은 큰 역할을 한다. 기술적 중심으로 사고를 하면 문제는 최적화다. 더 적은 자원으로 더 많은 것들을 달성하는 것이다. 기업에서 데이터 사이언스를 적용한다면 이 많은 것들이란 이윤일 가능성이 크다. 시장의 이윤의 창출은 불편의 해결에서 나온다. 스타트업이 성장하는 방법은 많은 사람들의 불편함(큰 시장)을 고유한 기술(적은 비용)으로 해결하여 큰 이윤을 창출하는 것이다. 미국에서 우버가 폭팔적으로 성장한 배경 중 하나는 미국의 고속도로 위주로 설계된 미국의 교통 시스템 내에서 대중교통 이용이 불편하기 때문이다. 자차를 운전하면 된다지만 미국 대도시의 교통 체증이 만만치 않다. 교통 체증보다 더 무서운 것이 주차지옥이다. 거기다 이런 승차 공유 서비스는 승차 경험을 표준화한다. 우버란 플랫폼을 이용할 줄 알면 본인이 거주하는 도시뿐 아니라 다른 어느 도시에 가더라도 새로운 학습 비용을 지불하지 않고 교통 서비스를 이용할 수 있다. 우버가 갖고 있는 기술도 훌륭하지만, 그것보다 더 중요한 것은 무엇이 풀어야 할 문제인 지에 대한 문제 정의다. 여기서 흥미로운 것은 이 문제 정의에 최적화의 한계가 무엇이어야 할지는 사전에 명확히 정의되어야 할 필요가 없다는 것이다. 기업도 이윤 외에 사회적 책임 차원에서 많은 것들을 고려해야 한다. 그러나 스타트업이 투자 유치를 할 때 투자자로부터 어떻게 하면 성장을 더 할 수 있을지에 대한 질문을 받을 가능성은 크다. 그러나 어떻게 하면 성장을 좀더 천천히 하더라도 이윤 외에 다른 것을 고려해야 할지에 대해서 질문을 받을 가능성은 낮다. 기업도 사회적 책임이 있으니 윤리를 생각해야 한다. 그러나 기업에게 있어서 윤리란 우선순위에 있어 이윤의 뒤에 올 가능성이 크다.

하지만 정부는 문제 정의를 다르게 해야 한다. 시장과 정부의 영역이 다르기 때문이다. 정책은 강제적인 성격을 띈다. 시장의 상품과 서비스는 개인이 사고 싶으면 사고 싶지 않으면 사지 않을 수 있다. 세금은 내고 싶으면 내고 내고 싶지 않으면 내지 않을 수 있는 것이 아니다. 탈세는 범죄다. 국가가 그렇게 국민에게 의무를 요구했으니, 그 만한 책임을 져야 한다. 그리고 정부는 그 책임을 특정 국민이 아니라 모두에게 다 져야 한다. 정부에게 있어 윤리란 2순위가 아니라 1순위, 정책적 사고의 출발점이다.

구체적으로, 공공 부문의 데이터 사이언스는 제한된 최적화의 관점에서 문제를 정의해야 한다. 이 제한이란 다 같이 잘 살기 위해 조금의 불편함을 감수하는 사회적 원칙의 제도화다. 필자가 미국 유학 중에 가장 감명깊게 보았던 것 중에 하나는 공공 버스에 휠체어를 탄 장애인들이 탑승하는 것이었다. 한국에 30년이 넘는 시간을 살았지만, 그런 모습을 서울이든, 지방이든, 그 어느 곳에서도 단 한 번도 본 적이 없다. 미국에서 이런 모습을 볼 수 있는 건, 미국 사람들이 남달리 장애인을 존중하는 것도 아니고, 미국이 처음부터 그랬던 것도 아니다. 지난 한 세대에 일어난 변화다. 1990년에 미국 의회에서 통과된 미국장애인법(Americans with Disabilities Act)이 1960년대에 제정된 많은 차별금지법 중 하나인 민권법(Civil Rights Act)에서 한 걸음 더 나아가 장애인의 대중 교통 서비스를 그들의 당당한 권리로 인정했기 때문이다. 따라서 버스 회사가 장애인에 대한 배려를 하지 않으면, 그 행위는 처벌이, 소송의 대상이 된다. 휠체어를 탄 장애인 한 명을 탑승하기 위해서 많은 사람들이 불편해질 수 있다. 그 많은 사람들이 편해지기 위해 계속 불편히 살아왔을 사람을 돕는 것도 그 만큼 가치있는 일이다. 그것이 더 성숙한 사회로 가는 길이기 때문이다. 그 사람의 조건과 배경에 관계없이 사람이 사람이면 누려야 할 권리가 인권이다 (법 앞의 평등을 주장하는 민권은 인권의 일부이다). 헌법이란 정부의 조직을 구성하고 이러한 기본권을 정의한다. 헌법에 기초한 민주 정부의 역할은 모든 국민의 다양한 권리를 지키고 확장하는 것이다.

미국에서는 공공 부문에서 인공지능의 적용뿐 아니라 인공지능의 정책 적용의 평가와 감사에 대한 논의도 활발히 진행돼 왔다. 기계가 사람을 대체해 의사 결정을 내리면 비용이 줄어드는 것은 당연하다. 초기에 개발, 설치 비용은 클 수 있으나 운영 비용이 비교할 수 없을 만큼 적기 때문이다. 실리콘밸리의 기업들은 소수의 인원으로 글로벌 플랫폼을 운영하는 비밀이 여기에 있다. 기술의 힘이다. 사람이 아니라 기계가 의사 결정을 내리기 때문에 규모의 경제가 빨리 이루어지고, 그 규모를 저비용으로 유지할 수 있다. 그러나 여기서 문제가 있다. 인공지능은 하늘에서 뚝 떨어진 것이 아니다. 현재 상용화된 대부분의 인공지능은 기계학습으로 사람이 그 목적을 정하고, 데이터를 먹여서 만든다. 아이는 부모를 학습하지 않더라도, 모방한다. 대다수 인공지능이 블랙박스다. 정확히 인공지능이 무엇을 어떻게 배우는지 알기 쉽지 않고 이 과정을 설명하는 것 자체가 컴퓨터 과학에서 최근 각광받는 분야다. 문제는 쓰레기가 들어가면 쓰레기가 나오고 (garbage in, garbage out), 차별이 들어가면 차별이 나온다는 것이다 (bias in, bias out). 고성능의 인공지능을 만들기 위해서는 "빅"데이터가 필요한데, 데이터의 규모를 키우기 위해서는 쓰레기고, 차별이고 생각하지 않고 일단 규모를 키우는 경우가 많다. 어쨌든, 그렇게 해서 고성능 인공지능이 나오는 것은 분명하기 때문이다. 하지만 이 탄생비화를 생각하면 이 인공지능이 집단을 전혀 차별하지 않을 가능성은 0에 가깝다. 이것은 특별히 인공지능의 잘못도 아니고, 그것을 설계한 엔지니어의 잘못도 아니다. 영화와 다르게 여기서는 특정한 악당이 없다. 여기서 악은 우리 자신이다. 우리가 사는 사회가, 그렇게 많은 부분에서 부서지고 일그러진 모습을 하고 있다. 그렇다면 이들 인공지능의 차별을 막기 위해서 어떻게 제한을 둘 것인가, 그 근거는 무엇인가. 미국에서 이 인공지능 윤리, 공정성 문제의 출발점은 1964년에 제정된 민권법이다. 법 앞에 모든 집단은 평등하다. 그 논리의 연장선에서 사람이든, 인공지능이든 정책 결정을 내렸다면 그 결과물이 집단간의 차별을 야기해서는 안 된다. 이렇게 정의된 문제 내에서 많은 학자들과 실무자들이 머리를 맞대고 문제 해결을 위해 고민하고 있다. 우리 한국에 있어서, 미국의 민권법에 비교할 만한 것은 무엇인가? 미국 같은 경우는 인종차별이 민권법에서 가장 중요한 내용이었다. 우리에게는 어떠한 차별이 가장 심각한 차별인가? 성적 차별인가? 외국인에 대한 혐오인가? 산업 고도화의 관점에서 논의된 기존의 데이터 전략, 인공지능 전략에서는 이와 같은 고민의 부재했다. 그리고 그것이 디지털 전환을 제4차 산업혁명뿐 아니라 제2의 민주화로 봐야하는 이유다. 권리의 수호와 확장이 없이는 번영과 포용을 같이 가져다 주는 디지털 전환도 없다.

편리할 것은 편리해야 하고 불편해야 할 것은 불편해야 한다. 이것은 민주 국가에서 정책 운영의 가장 기본적인 원리다. 디지털 전환 시대에서도 이것은 마찬가지다. 희소한 자원으로 많은 사람들의 삶을 더 낫게 해야 하니 자원을 잘 써야 한다. 이 문제를 데이터 사이언스는 기존에 할 수 없던 규모로, 속도로, 비용으로 해결할 수 있다. 그것이 민간에서 이미 일어난 데이터 혁명이 공공 부문에도 들어와야 하는 이유다. 그러나 시장과 정부는 다르다. 민주 정부는 다르다. 정부의 문제는 그 출발부터 최적화가 아니라 제한된 최적화다. 정부에게 윤리란 선택이 아니라 의무이며, 차순위가 아니라 일순위이기 때문이다. 더 성숙한 사회로 가려면, 현실뿐 아니라 이상을 보아야 한다. 기존의 차별을 답습하는 것이 아니라, 이것을 극복할 방법을 찾아나가야 한다. 결국 데이터는 스스로 말하지 않고, 인공지능은 무에서 유를 창조하지 않는다. 데이터에서 찾아야 할 열쇠가 무엇일지, 인공지능이 풀어야 할 문제가 무엇인지, 그 기준과 원칙을 이제 우리가 스스로 정해나가야 한다.
